#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
    *.tar*)
        tar tf "$file" ;;
    *.zip)
        unzip -l "$file" ;;
    *.rar)
        unrar l "$file" ;;
    *.7z)
        7z l "$file" ;;
    *.mkv|*.mp4|*.avi|*.ts|*.webm|*.mov|*.wmv|*.flv|*.m4v|*.mpg|*.mpeg|*.ogv|*.vob)
        ffprobe -pretty -hide_banner "$file" 2>&1 ;;
    *.wav|*.mp3|*.flac|*.m4[ab]|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus)
        ffprobe -pretty -hide_banner "$file" 2>&1 ;;
    *.bmp|*.jpg|*.jpeg|*.png|*.gif|*.xpm|*.svg)
        preview "$file" "$@" ;;
    *) 
        info=$(file -Lib "$file")
        if printf '%s\n' "$info" | rg -qi -e 'text' -e 'ascii' -e 'utf-8'; then
            bat -p "$file" 
        else
            printf '%s' "$info"
        fi
        ;;
esac
return 127 # nonzero retcode required for lf previews to reload
