#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

  QUOTES=(
    "Peaceful days are over. Let's survive.\n  --女神異聞録デビルサバイバー"
    "何でもは知らないわよ。知ってることだけ。\n  --羽川翼"
    "その幻想をぶち殺す！\n  --上条当麻"
    "未来を買い戻す\n  --余賀公麿"
    "今後も救世主たらんことを。\n  --JUIZ"
  )
  
  # Print a randomly-chosen message:
  echo $QUOTES[$(($RANDOM % ${#QUOTES} + 1))]

} >&2
