#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

echo -n "Peaceful days are over."
sleep 1
echo -n "\nLet's survive."
sleep 2

} >&2
