#!/bin/sh

# Configuration
source "$XDG_CACHE_HOME/wal/colors.sh"

bspc monitor -d 壱 弐 参 肆 伍 陸 漆 捌 玖

bspc config automatic_scheme    alternate

bspc config border_width        1
bspc config window_gap          8

bspc config top_padding         30
bspc config bottom_padding      4
bspc config left_padding        4
bspc config right_padding       4

bspc config split_ratio         0.55
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      any

bspc config normal_border_color     "$color3"
bspc config active_border_color     "$color3"
bspc config focused_border_color    "$color6"
bspc config presel_feedback_color   "$color3"

bspc config external_rules_command  "$XDG_CONFIG_HOME/bspwm/extensions/external_rules"

# Startup actions
if [ "$1" = 0 ]; then
    bspc rule -a KeePassXC -o hidden=on sticky=on
    keepassxc &
    if [ $(autorandr --current) == "undocked" ]; then
        bspc rule -a firefox:Navigator -o desktop='^1' locked=on
        bspc rule -a Helium:helium -o desktop='^2' locked=on

        firefox &
        helium-browser &
    else
        bspc rule -a firefox:Navigator -o desktop='^1' locked=on
        bspc node @'^2':/ -i
        bspc node @'^2':/ -p east -o 0.5 -i

        bspc rule -a Helium:helium -o node=@'^2':/1 locked=on
        bspc rule -a rmpc -o node=@'^2':/2 locked=on

        firefox &
        helium-browser &
        alacritty --class rmpc --title rmpc -e rmpc &
        sleep 1
        helium-browser --new-window https://game.mahjongsoul.com/index.html
    fi
# Reload configuration actions
else
    # Redundancy check to avoid multiple calls
    if bspc query -D --names | rg -q "Desktop"; then
        # Move workspaces to active monitor & delete default workspace
        monitor=$(xrandr --listactivemonitors | awk 'NR>1 {print $NF}')
        for desktop in $(bspc query -D --names); do
            bspc desktop "$desktop" -m "$monitor"
        done
        bspc desktop "Desktop" --remove

        # Monitor-specific cleanup
        case "$(autorandr --current)" in
            docked)
                bspc monitor DisplayPort-1 --remove
                pkill redshift
                redshift &
                ;;
            tv)
                bspc monitor DisplayPort-3 --remove
                pkill redshift
                ;;
        esac

        # Reload configuration
        bspc wm -r
    fi
fi

# (Re)launch services
wal -R
pgrep bspswallow || "$XDG_CONFIG_HOME/bspwm/extensions/bspswallow" &
"$XDG_CONFIG_HOME/dunst/launch.sh"
"$XDG_CONFIG_HOME/polybar/launch.sh"
