dynvariables:
  user: whoami

actions:
  pre:
    prezto-install: scripts/prezto-install.zsh

  post:
    dunst-link: scripts/dunst-link.sh
    link-scripts: scripts/link-scripts.sh
    vim-plug: scripts/vim-plug.sh
    wal-apply: wal --theme blank

config:
  create: true
  backup: false
  dotpath: dotfiles

dotfiles:
  # base
  f_gitconfig:
    dst: ~/.gitconfig
    src: base/.gitconfig
  f_nvim:
    dst: ~/.config/nvim/init.vim
    src: base/.config/nvim/init.vim
    actions:
      - vim-plug
  f_ranger:
    dst: ~/.config/ranger/
    src: base/.config/ranger/
  f_wal:
    dst: ~/.config/wal/colorschemes/dark/blank.json
    src: base/.config/wal/colorschemes/dark/blank.json
    actions:
      - wal-apply
  f_zprezto:
    dst: ~/.zprezto/runcoms/
    src: base/.zprezto/runcoms/
    actions:
      - prezto-install
  f_zprezto_theme:
    dst: ~/.zprezto/modules/prompt/functions/prompt_kyoto_setup
    src: base/.zprezto/modules/prompt/functions/prompt_kyoto_setup

  # core
  f_alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: core/.config/alacritty/alacritty.yml
  f_fcitx-config:
    dst: ~/.config/fcitx/config
    src: core/.config/fcitx/config
  f_fcitx-skin:
    dst: ~/.config/fcitx/skin/dark/fcitx_skin.conf
    src: core/.config/fcitx/skin/dark/fcitx_skin.conf
  f_fcitx-skin-conf:
    dst: ~/.config/fcitx/conf/fcitx-classic-ui.config
    src: core/.config/fcitx/conf/fcitx-classic-ui.config
  f_gtk2:
    dst: ~/.gtkrc-2.0
    src: core/.gtkrc-2.0
  f_gtk3:
    dst: ~/.config/gtk-3.0/settings.ini
    src: core/.config/gtk-3.0/settings.ini
  f_gtk_icons:
    dst: ~/.icons/
    src: core/.icons/
  f_gtk_themes:
    dst: ~/.themes/
    src: core/.themes/
  f_mpd:
    dst: ~/.config/mpd/mpd.conf
    src: core/.config/mpd/mpd.conf
  f_mpv:
    dst: ~/.config/mpv/
    src: core/.config/mpv/
  f_ncmpcpp:
    dst: ~/.config/ncmpcpp/
    src: core/.config/ncmpcpp/
    cmpignore:
      - error.log
  f_qbittorrent:
    dst: ~/.config/qBittorrent/rss/feeds.json
    src: core/.config/qBittorrent/rss/feeds.json
  f_radare2rc:
    dst: ~/.radare2rc
    src: core/.radare2rc
  f_rofi:
    dst: ~/.config/rofi/config
    src: core/.config/rofi/config
  f_scripts:
    dst: ~/.local/src/scripts/
    src: core/.local/src/scripts/
    actions:
      - link-scripts
  f_syncplay:
    dst: /home/blankaex/.config/syncplay.ini
    src: core/.config/syncplay.ini

  # desktop
  f_d_bspwm:
    dst: ~/.config/bspwm/bspwmrc
    src: desktop/.config/bspwm/bspwmrc
  f_d_dunstrc:
    dst: ~/.config/wal/templates/dunstrc
    src: desktop/.config/wal/templates/dunstrc
    actions:
      - dunst-link
  f_d_fehbg:
    dst: ~/.fehbg
    src: desktop/.fehbg
  f_d_i3:
    dst: ~/.config/i3/
    src: desktop/.config/i3/
  f_d_sxhkd:
    dst: ~/.config/sxhkd/sxhkdrc
    src: desktop/.config/sxhkd/sxhkdrc
  f_d_polybar:
    dst: ~/.config/polybar/
    src: desktop/.config/polybar/
  f_d_xinit:
    dst: ~/.xinitrc
    src: desktop/.xinitrc

  # laptop
  f_l_dunstrc:
    dst: ~/.config/wal/templates/dunstrc
    src: laptop/.config/wal/templates/dunstrc
    actions:
      - dunst-link
  f_l_fehbg:
    dst: ~/.fehbg
    src: laptop/.fehbg
  f_l_i3:
    dst: ~/.config/i3/
    src: laptop/.config/i3/
  f_l_polybar:
    dst: ~/.config/polybar/
    src: laptop/.config/polybar/
  f_l_xinit:
    dst: ~/.xinitrc
    src: laptop/.xinitrc

profiles:
  base:
    dotfiles:
      - f_gitconfig
      - f_nvim
      - f_ranger
      - f_wal
      - f_zprezto
      - f_zprezto_theme

  core:
    include:
      - base
    dotfiles:
      - f_alacritty
      - f_fcitx-config
      - f_fcitx-skin
      - f_fcitx-skin-conf
      - f_gtk2
      - f_gtk3
      - f_gtk_icons
      - f_gtk_themes
      - f_mpd
      - f_mpv
      - f_ncmpcpp
      - f_qbittorrent
      - f_radare2rc
      - f_rofi
      - f_scripts
      - f_syncplay

  server:
    include:
      - base

  desktop:
    include:
      - core
    dotfiles:
      - f_d_bspwm
      - f_d_dunstrc
      - f_d_fehbg
      - f_d_i3
      - f_d_polybar
      - f_d_sxhkd
      - f_d_xinit

  laptop:
    include:
      - core
    dotfiles:
      - f_l_dunstrc
      - f_l_fehbg
      - f_l_i3
      - f_l_polybar
      - f_l_xinit
