#!/usr/bin/env zsh

cleanup() {
	cleaner
	kill "$UEBERZUGPID"
	pkill -f "tail -f $LF_UEBERZUG_TEMPDIR/fifo"
	rm -rf "$LF_UEBERZUG_TEMPDIR"
}
trap cleanup INT HUP

# Set up temporary directory.
export LF_UEBERZUG_TEMPDIR="$(mktemp -d -t lf-ueberzug-XXXXXX)"

# Launch ueberzug & lf.
mkfifo "$LF_UEBERZUG_TEMPDIR/fifo"
tail -f "$LF_UEBERZUG_TEMPDIR/fifo" | ueberzugpp layer --silent &
UEBERZUGPID=$!
export PATH="$PATH:${ZSH_ARGZERO:A:h}"
lf $1
cleanup
