#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$LF_UEBERZUG_TEMPDIR/fifo"
	{
	"action": "add", "identifier": "lf-preview",
	"path": "$1", "x": $4, "y": $5, "width": $2, "height": $3,
	"scaler": "contain"
	}
	EOF
}

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
*.tar*) tar tf "$file" ;;
*.zip) unzip -l "$file" ;;
*.rar) unrar l "$file" ;;
*.7z) 7z l "$file" ;;
*.avi|*.mp4|*.mkv|*.webm)
	thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
	ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.pdf)
	thumbnail="$LF_UEBERZUG_TEMPDIR/thumbnail.png"
	gs -o "$thumbnail" -sDEVICE=png16m -dLastPage=1 "$file" >/dev/null
	preview "$thumbnail" "$@"
	;;
*.jpg|*.jpeg|*.png|*.bmp|*.svg|*.gif)
	preview "$file" "$@" ;;
*) 
    info=$(file -Lib "$file")
    if printf '%s\n' "$info" | rg -q -e 'text' -e 'ascii' -e 'utf-8'; then
        bat -p --color=always "$file" 
    else
        printf '%s' "$info"
    fi
    ;;
esac
return 127 # nonzero retcode required for lf previews to reload
