#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$1")

case "$title:$class:$instance" in
    # chrome screen sharing widget
    *共有しています*::)
        echo "hidden=on sticky=on"
        ;;
    # runelite launcher loading window
    "RuneLite Launcher":*runelite*:*)
        echo "state=floating"
        ;;
    # runelite picture-in-picture
    "Picture in Picture":*runelite*:*)
        echo "state=floating"
        ;;
    # master duel
    "masterduel":*steam*:*)
        echo "state=pseudo_tiled"
        ;;
esac
