#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  source "/etc/profile.d/autojump.sh"
fi

# Vi mode
bindkey -v
bindkey -v '^?' backward-delete-char
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word

zstyle ':completion:*' menu select
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Command editing
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line

# Aliases
alias diff='diff --color=auto'
alias erogays='vboxmanage startvm erogays'
alias jantama='vivaldi-stable --new-window --start-fullscreen game.mahjongsoul.com'
alias mozc-dic='/usr/lib/mozc/mozc_tool --mode=dictionary_tool'
alias ncmpcpp='ncmpcpp --config $HOME/.config/ncmpcpp/config --bindings $HOME/.config/ncmpcpp/bindings'
alias ncmpcpp-tmux='TERM=xterm-256color tmux new-session "tmux source-file ~/.config/ncmpcpp/session.tmux"'
alias syncplay='syncplay --no-store --no-gui -p $SYNCPLAY_PASSWORD'
alias xclip='xclip -selection clipboard'
alias :q='exit'

# Functions
function mkcdir()
{
    /bin/mkdir -p $@ && cd "$_"
}

function 0x0()
{
    curl -F file=@"$1" https://0x0.st
}

function spengbab()
{
    spongemock $@ | xclip
}
