#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  source "/etc/profile.d/autojump.sh"
fi

# Vi mode
bindkey -v
bindkey -v '^?' backward-delete-char
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word

zstyle ':completion:*' menu select
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Command editing
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line

# Aliases (flags)
alias cp='cp -iv'
alias mv='mv -iv'
alias diff='diff --color=auto'
alias xclip='xclip -selection clipboard'
alias ncmpcpp='ncmpcpp --config $HOME/.config/ncmpcpp/config --bindings $HOME/.config/ncmpcpp/bindings'

# Aliases (programs)
alias lf='lf-ueberzug'
alias erogays='vboxmanage startvm erogays'
alias mozc-dic='/usr/lib/mozc/mozc_tool --mode=dictionary_tool'
